pipeline {

agent any

stages {

stage('Checkout') {

steps {

checkout scm

}

}

stage('Docker') {

steps {

sh 'chmod +x scripts/build.sh'

sh './scripts/build.sh'

}

}

stage('Terraform') {

steps {

sh 'chmod +x scripts/deploy.sh'

sh './scripts/deploy.sh'

}

}

}

}