pipeline {

 agent any

 stages {

   stage('Checkout') {
     steps {
       git 'https://github.com/YOUR_USERNAME/ecommerce-devops-project.git'
     }
   }

   stage('Build Docker Image') {
     steps {
       sh '''
       cd app
       docker build -t ecommerce-app:v1 .
       '''
     }
   }

   stage('Deploy') {
     steps {
       sh '''
       docker stop ecommerce-app || true
       docker rm ecommerce-app || true

       docker run -d \
       --name ecommerce-app \
       -p 80:80 \
       ecommerce-app:v1
       '''
     }
   }

   stage('Health Check') {
     steps {
       sh 'curl http://localhost'
     }
   }

 }

}